export const FETCH_ALL_WORKOUT_INITIATED = 'FETCH_ALL_WORKOUT_INITIATED'
export const FETCH_ALL_WORKOUT_SUCCESS = 'FETCH_ALL_WORKOUT_SUCCESS'
export const FETCH_ALL_WORKOUT_FAILED = 'FETCH_ALL_WORKOUT_FAILED'

export const CREATE_WORKOUT_INITIATED = 'CREATE_WORKOUT_INITIATED'
export const CREATE_WORKOUT_SUCCESS = 'CREATE_WORKOUT_SUCCESS'
export const CREATE_WORKOUT_FAILED = 'CREATE_WORKOUT_FAILED'

export const DELETE_WORKOUT_INITIATED = 'DELETE_WORKOUT_INITIATED'
export const DELETE_WORKOUT_SUCCESS = 'DELETE_WORKOUT_SUCCESS'
export const DELETE_WORKOUT_FAILED = 'DELETE_WORKOUT_FAILED'

export const UPDATE_WORKOUT_INITIATED = 'UPDATE_WORKOUT_INITIATED'
export const UPDATE_WORKOUT_SUCCESS = 'UPDATE_WORKOUT_SUCCESS'
export const UPDATE_WORKOUT_FAILED = 'UPDATE_WORKOUT_FAILED'
